Repository Sofiav014/ISIS3510-Team32-Kotlin, pull requests merged in 2025-05, with the labels that each got.

#66 fix: added filter to include only upcoming bookings
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailFragment.kt
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailViewModel.kt
Labels: bug

#63 refactor: moved viewmodels to the correct folder
  app/src/main/java/com/example/sporthub/ui/findVenues/FindVenuesFragment.kt
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailFragment.kt
  app/src/main/java/com/example/sporthub/ui/venueList/VenueListFragment.kt
  app/src/main/java/com/example/sporthub/viewmodel/FindVenuesViewModel.kt
  app/src/main/java/com/example/sporthub/viewmodel/VenueDetailViewModel.kt
Labels: refactor

#76 Multithreading implementation for Create Booking and logo implementation
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sporthub/data/repository/BookingRepository.kt
  app/src/main/java/com/example/sporthub/ui/createBooking/CreateBookingFragment.kt
  app/src/main/java/com/example/sporthub/viewmodel/CreateBookingViewModel.kt
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/logo_round.png
Labels: enhancement

#78 Chaching strategies implementation: LRU cache and chaching of images …
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sporthub/ui/home/HomeFragment.kt
  app/src/main/java/com/example/sporthub/ui/home/RecommendedBookingsAdapter.kt
  app/src/main/java/com/example/sporthub/ui/home/UpcomingBookingsAdapter.kt
  app/src/main/java/com/example/sporthub/ui/home/viewholder/RecommendedBookingViewHolder.kt
  app/src/main/java/com/example/sporthub/ui/home/viewholder/UpcomingBookingViewHolder.kt
  app/src/main/java/com/example/sporthub/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/logoclean.png
  app/src/main/res/drawable/logoround.png
  app/src/main/res/drawable/logosporthubsmall.png
  app/src/main/res/drawable/placeholder_image.png
Labels: enhancement

#82 Feat/80 implement local storage venue list
  app/src/main/java/com/example/sporthub/data/model/CachedVenue.kt
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailFragment.kt
  app/src/main/java/com/example/sporthub/ui/venueList/VenueAdapter.kt
  app/src/main/java/com/example/sporthub/ui/venueList/VenueListFragment.kt
  app/src/main/java/com/example/sporthub/utils/ImageUrlStore.kt
  app/src/main/java/com/example/sporthub/utils/LRUCache.kt
  app/src/main/java/com/example/sporthub/viewmodel/FindVenuesViewModel.kt
Labels: enhancement

#85 Develop-fix
  app/src/main/java/com/example/sporthub/SportHubApplication.kt
  app/src/main/java/com/example/sporthub/data/model/CachedVenue.kt
  app/src/main/java/com/example/sporthub/data/repository/HomeRepository.kt
  app/src/main/java/com/example/sporthub/data/repository/UserRepository.kt
  app/src/main/java/com/example/sporthub/ui/MainActivity.kt
  app/src/main/java/com/example/sporthub/ui/home/HomeFragment.kt
  app/src/main/java/com/example/sporthub/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/sporthub/ui/profile/edit/EditBirthDateActivity.kt
  app/src/main/java/com/example/sporthub/ui/profile/edit/EditGenderActivity.kt
  app/src/main/java/com/example/sporthub/ui/profile/edit/EditNameActivity.kt
  app/src/main/java/com/example/sporthub/ui/profile/edit/EditSportsActivity.kt
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailFragment.kt
  app/src/main/java/com/example/sporthub/ui/venueList/VenueAdapter.kt
  app/src/main/java/com/example/sporthub/ui/venueList/VenueListFragment.kt
  app/src/main/java/com/example/sporthub/utils/ImageUrlStore.kt
  app/src/main/java/com/example/sporthub/utils/LRUCache.kt
  app/src/main/java/com/example/sporthub/utils/LocalThemeManager.kt
  app/src/main/java/com/example/sporthub/utils/ThemeSwitcher.kt
  app/src/main/java/com/example/sporthub/viewmodel/FindVenuesViewModel.kt
  app/src/main/java/com/example/sporthub/viewmodel/ProfileViewModel.kt
Labels: bug

#95 Feat/86 calendar view
  app/src/main/java/com/example/sporthub/ui/bookings/BookingAdapter.kt
  app/src/main/java/com/example/sporthub/ui/bookings/BookingsFragment.kt
  app/src/main/java/com/example/sporthub/viewmodel/BookingsViewModel.kt
  app/src/main/res/layout/fragment_bookings.xml
  app/src/main/res/layout/item_my_booking.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: enhancement

#92 Feat/87 like venues button
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueDetailFragment.kt
  app/src/main/java/com/example/sporthub/viewmodel/VenueDetailViewModel.kt
  app/src/main/res/drawable/ic_heart_filled.xml
Labels: bug, enhancement

#101 Feat/84 booking detail
  app/build.gradle.kts
  app/src/main/java/com/example/sporthub/SportHubApplication.kt
  app/src/main/java/com/example/sporthub/data/repository/BookingRepository.kt
  app/src/main/java/com/example/sporthub/ui/MainActivity.kt
  app/src/main/java/com/example/sporthub/ui/bookingDetail/BookingDetailAdapter.kt
  app/src/main/java/com/example/sporthub/ui/bookingDetail/BookingDetailFragment.kt
  app/src/main/java/com/example/sporthub/ui/bookings/BookingsAdapter.kt
  app/src/main/java/com/example/sporthub/ui/bookings/BookingsFragment.kt
  app/src/main/java/com/example/sporthub/ui/createBooking/CreateBookingFragment.kt
  app/src/main/java/com/example/sporthub/ui/home/HomeFragment.kt
  app/src/main/java/com/example/sporthub/ui/home/UpcomingBookingsAdapter.kt
  app/src/main/java/com/example/sporthub/ui/venueDetail/VenueBookingAdapter.kt
  app/src/main/java/com/example/sporthub/viewmodel/BookingDetailViewModel.kt
  app/src/main/java/com/example/sporthub/viewmodel/CreateBookingViewModel.kt
  app/src/main/java/com/example/sporthub/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/chip_background.xml
  app/src/main/res/layout/fragment_booking_detail.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#104 fix: Implemented support for Dark theme inside booking detail view.
  app/src/main/res/layout/fragment_booking_detail.xml
Labels: bug

#114 Feat/110 caching for calendar view
  app/src/main/java/com/example/sporthub/viewmodel/BookingsViewModel.kt
Labels: enhancement
